apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pong-ladder-home-arpa
  namespace: pingpong
spec:
  secretName: pong-ladder-home-arpa-tls
  dnsNames:
    - pong-ladder.home.arpa
  issuerRef:
    name: step-ca
    kind: ClusterIssuer
