apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: pong-ladder-canonical-host
  namespace: pingpong
spec:
  redirectRegex:
    regex: '^https?://www\.pongladder\.com/(.*)'
    replacement: 'https://pongladder.com/${1}'
    permanent: true
