apiVersion: v1
kind: Service
metadata:
  name: pong-ladder
  namespace: pingpong
  labels:
    app.kubernetes.io/name: pong-ladder
    app.kubernetes.io/part-of: pong-ladder
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: pong-ladder
  ports:
    - name: http
      port: 3000
      targetPort: http
